# Generated by Django 2.1.1 on 2018-10-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181030_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_manage_posts', 'Managing posts'),)},
        ),
    ]
